spring.application.name=veiculos
spring.datasource.url=jdbc:mysql://localhost:3306/veiculos_db
spring.datasource.username=root
spring.datasource.password=21101985

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true